
luet_version: "0.8.11"

packages:
  - "repository/luet"
  - "system/luet"

install:
    packages:
      - "utils/charty"
rootfs_dir: "rootfs"

debug: false
upgrade: true

features:
  luet_box: false
box_dns: 8.8.8.8
repositories: |
  - name: "mocaccino-repository-index"
    description: "MocaccinoOS Repository index"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-repository-index"
  - name: "mocaccino-micro"
    description: "MocaccinoOS micro"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-micro"
  - name: "mocaccino-extra"
    description: "MocaccinoOS extra"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-extra"
  - name: "luet"
    type: "http"
    enable: true
    priority: 1
    urls:
    - "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"