
luet_version: "0.8.11"

packages_dir: "/somewhere/in/your/system"
rootfs_dir: "rootfs"

debug: false

repositories: |
  - name: "mocaccino-repository-index"
    description: "MocaccinoOS Repository index"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-repository-index"
  - name: "mocaccino-micro"
    description: "MocaccinoOS micro"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-micro"
  - name: "mocaccino-extra"
    description: "MocaccinoOS extra"
    type: "http"
    enable: true
    cached: true
    priority: 1
    urls:
    - "https://get.mocaccino.org/mocaccino-extra"
  - name: "luet"
    type: "http"
    enable: true
    priority: 1
    urls:
    - "https://raw.githubusercontent.com/Luet-lab/luet-repo/gh-pages"